# Generated by Django 5.2.4 on 2025-08-30 23:13

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['day_of_week', 'clinic_slot']},
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='description',
        ),
        migrations.AddField(
            model_name='clinic',
            name='default_close_time',
            field=models.TimeField(default=datetime.time(23, 0)),
        ),
        migrations.AddField(
            model_name='clinic',
            name='default_open_time',
            field=models.TimeField(default=datetime.time(13, 0)),
        ),
        migrations.AddField(
            model_name='clinic',
            name='slot_duration_hours',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ClinicSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_added_by', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clinic')),
                ('day_of_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.daysofweek')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('clinic', 'start_time')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='clinic_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.clinicslot'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor', 'day_of_week', 'clinic_slot')},
        ),
        migrations.DeleteModel(
            name='ClinicSchedule',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='start_time',
        ),
    ]
