# Generated by Django 5.2.4 on 2025-08-30 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_doctorschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clinicslot',
            unique_together=set(),
        ),
    ]
