# Generated by Django 5.0.7 on 2025-10-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appointment_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='price',
            new_name='service_price',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('examination', 'Examination')], default='consultation', max_length=20),
        ),
    ]
