# Generated by Django 5.2.4 on 2025-09-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_clinicslot_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicslot',
            name='day_of_week',
        ),
    ]
