# Generated by Django 5.0.7 on 2025-10-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_price_appointment_service_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(max_length=20),
        ),
    ]
