# Generated by Django 5.2.4 on 2025-09-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_clinicslot_day_of_week'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together=set(),
        ),
    ]
