# Generated by Django 5.2.4 on 2025-10-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_appointment_service_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['day_of_week']},
        ),
        migrations.AlterField(
            model_name='clinic',
            name='slot_duration_hours',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='clinic_slot',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='clinic_slot',
            field=models.ManyToManyField(to='app.clinicslot'),
        ),
    ]
