# Generated by Django 5.2.4 on 2025-08-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_doctor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('CARDIOLOGY', 'Cardiology'), ('DERMATOLOGY', 'Dermatology'), ('PEDIATRICS', 'Pediatrics'), ('ORTHOPEDICS', 'Orthopedics'), ('GYNECOLOGY', 'Gynecology'), ('ENT', 'ENT'), ('DENTISTRY', 'Dentistry'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('COSMETIC', 'Cosmetic'), ('GENERAL', 'General Medicine')], default='GENERAL', max_length=20),
        ),
    ]
