# Generated by Django 5.2.4 on 2025-08-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_doctor_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
