# Generated by Django 5.0.7 on 2025-08-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_patient_age_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient',
            table='Patient',
        ),
    ]
