# Generated by Django 5.0.7 on 2025-08-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_patient_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='full_name',
            new_name='name',
        ),
    ]
